### ISSUE TITLE
keyple-plugin-stub: wrong design for StubPluginFactory & StubPluginImpl

### ISSUE THREAD

**Issue by pterr** [eclipse/keyple-java#129]
Currently StubPluginImpl isn't a singleton: several instances of the plugin could potentially be created.
StubPoolPluginImpl shouldn't contains a StubPluginImpl as attributes. The only link between StubPoolPluginImpl & StubPluginImpl is that both manage SeReader based on StubReaderImpl.

**Comment by odelcroi** [comment]
Actually, the SeProxyService is responsible for not creating multiple instances of StubPluginImpl. 
StubPoolPluginImpl wraps a StubPluginImpl because it enhances its features with "pool" methods (alternative to extension with more flexilibity)
So I don't think the design is wrong, or am I missing something?

**Comment by jeanpierrefortune** [comment]
I think the problem is elsewhere. If we have an application that uses the StubPlugin for PO and the StubPoolPlugin for SAM, then there will be two usages of the StubPlugin in two different locations in the system: in the main application and in the StubPoolPlugin.
In addition to adding confusion, this mechanism goes against the principle of StubPoolPlugin, whose purpose is to be able to provide an arbitrary (potentially large) number of identical readers.
The solution probably involves a new design of the StubPoolPlugin API. We would no longer pass a StubPluginImpl as a constructor parameter but a list of groupReferences and their associated SE.
During allocation, the StubPoolPlugin creates a StubReader on the fly in which an SE is inserted.
The idea being to reproduce as closely as possible the functioning of an HSM, it seems preferable to carry out the allocation of readers in this way.
In the new API, the plugStubPoolReader and unplugStubPoolReader methods are removed.
I will try to propose an evolution of the API soon.

**Comment by odelcroi** [comment]
You are right, in the usecase you mention, two plugins will be register in the seProxy :  
- 1 StubPlugin for PO
- 1 PoolStubPlugin for SAM. then you can create as many reader as you need with plugStubPoolReader() and then allocate them with the method allocateReader()
Still not seeing the issue here?

**Comment by odelcroi** [comment]
Change : 
-  StubPluginFactory   allows defining a custom name for StubPlugin
-  StubPoolPluginFactory allows defining a custom name for StubPoolPlugin
-  StubPoolPluginFactory doesn't use StubPluginFactory anymore

Does not change : 
- StubPoolPlugin wraps a StubPlugin in its implementation
