### ISSUE TITLE
Correct the SamResourceManager in the PC/SC case

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#148]
The SAM reader observation mechanism is not compatible for use in this class.

**Comment by jeanpierrefortune** [comment]
The SamResourceManager PC/SC asks questions that we may not have answered yet!

To put the ideas in place, I give the context back:

- it is a question of dynamically allocating SAM resources to an application (in the form of cards inserted in a PC/SC reader)

- so it is necessary:
   - monitor reader insertions/removals 
   - monitor card insertions/removals in readers
   - manage the case where the card is already present in the reader when the reader is inserted
- the application may also have to manage PO PC/SC readers.

The tricky points are:
- The double monitoring of the PC/SC plugin
   - we can have two observers with in each one a specifc filter (regex) on the names of the readers so that each one "tracks" the readers that are relevant to it (e.g. "Identive.\*" for SAM and"(ASK|ACR).\*" for PO)
   - but the assignment of observers (of Reader) with addObserver leads to annoying behaviors: the addition of the 1st observer (e. g. SAM) starts the observation thread which makes the inventory of the readers present and notifies the only observer present.
     When adding a 2nd observer (PO), the observation thread does nothing more and therefore the new observer is not notified of the presence of the readers (and potentially of the reader that concerns it).
   - the notification of the readers present at startup therefore works well but only for the first observer!
- The case of the card already inserted in the reader when plugged in
   - in the SamResourceManager, we want to add an SE observer to any new reader inserted but at the moment, the notification of the presence of an already inserted SE is not performed.
     When adding the SE observer, we could call isSePresent() to manage this case, but there is a risk of concurrency and double allocation if the same thing is done at the same time by the observer (insertion just after the reader is connected)

It is therefore necessary to define a method and/or mechanisms to address these points.
Any contribution to solving this issue is welcome.

**Comment by odelcroi** [comment]
"It is a question of dynamically allocating SAM resources to an application (in the form of cards inserted in a PC/SC reader):"

Then the SamResourceManager has two main responsibilities : 
(1) - manage the available resources
(2) - allocate one resource when requested if one is available. 

To answer responsibilities (1), as you stated we can rely on the observation mechanism. But not only, we can also use in combination the explicit methods to get the status of the readers and SE :  getReaders and isSePresent(). The management of available resources can be real-time, or it can be updated when one request is made on (2)

Answering (2) should be precisely specified : 
- if one resource is available, allocate it. it should somehow be marked as busy. Is there a timeout to release it, if the requester doesn't do it?
- if no resource is available because there are none connected, what should we return? 
- if no resource is available because they are busy, should be wait? how long time?

**Comment by jeanpierrefortune** [comment]
After reviewing, the case of the card already inserted in the reader is not a problem. It was an implementation error that put me on the wrong path...

Concerning the SamResourceManager itself and the dynamic allocation of resources, the best answer is probably to create a ReaderPoolPlugin object based on a subset of the available PC/SC readers.

This would have the advantage of simplifying the SamResourceManager class, which currently takes into account both plugin models.

However, it remains the question of how to create independent subsets from a single plugin (PC/SC).

The idea is to rely on the existing plugin and create a kind of wrapper that redirects commands and notifications according to rules based on reader names.
