### ISSUE TITLE
Add mirroring of card data for Calypso PO

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-java#232]
In order to solve future new features (such as #232), it would be helpful to have an image of the information retrieved from the PO during a transaction.
The main idea is to populate a local database (ideally as an extension of CalypsoPo) throughout the execution of a PoTransaction.
CalypsoPo will have new protected setters (accessible from PoTransaction) and public getters (accessible from the application).
The data concerned are the files and all non-volatile statuses of the PO (such as the PIN presentation counter).
The current API (parser index in return for prepare commands) could be conserved to maintain backward compatibility with existing application implementations (at least for some time).

**Comment by pterr** [comment]
The Calypso Keyple extension provides a **high level API** to select a Calypso, to prepare & process PO commands (defined in the package org.eclipse.keyple.calypso.**transaction**)
The way de configure the PO selection and the PO commands is an achievement, involving simple functional commands with simple functional parameters, far from the complexity of the configuration of the PO APDU commands.

- We recover the status and the startup information of the selected PO through the CalypsoPo object.
- A PoTransaction object allows to manage the functionals commands to operate with the CalypsoPo.

But the current PoTransaction presents a strong **weakness**: the current way to recover is based on a “**low level** API” from APDU response parser (defined in the package org.eclipse.keyple.calypso.**command.po.parser**): and the way based “command index” to identify what APDU response parser is related to a specific prepared PO command is complex to use. The command index has been defined in order to provide at the command preparation state links to recover PO responses that will be initialize only during the processing of the prepared PO commands.

The purpose of this evolution is to fully hide the complexity of the low level APDU parser API, and to avoid need to parse specific command responses.
The solution is to fill the CalypsoPo & PoTransaction objects with the data parsed in the PO responses:

- To add getters to CalypsoPo to recover **PO data & status**:
  - the data of the PO file structure: file data read or write during the PoTransaction.
  - Stored Value data: amount (current value / unknown), last reload information, last debit information…
  - PO status: like the invalidation status, the PIN status (number of attempts remaining), …
- To add getters to PoTransaction to recover **transaction states**:
  - PIN verifications state (successful/failed/unknown),
  - secure sessions state (open, closed after a successful authentication, closed after a failed authentication, closed after a cancelled authentication, unknown),
  - stored value transaction state (reload authentication processed/failed, same for debit)

**Comment by jeanpierrefortune** [comment]
Feature added in version 0.9
