### ISSUE TITLE
calypso : sam manager feedbacks with pcsc plugin

### ISSUE THREAD

**Issue by odelcroi** [eclipse/keyple-java#255]
Some feedbacks about using the sam manager with a pcsc and stub reader :
- when no resources are available, it returns null: should it be an exception?
- the sam manager could be a singleton (or declare to the seProxy?), it would be easier to initialize it and use it.
- I would like to check if my setup is successful with a size() method on the created resources.

Some feedbacks about the implementation : 
- SamResourceManager manages pool plugin, observable plugin, and reader plugin in only one implementation whereas the behavior is totally different. It would be good to split it into two implementations. #split 
- If the plugin is observable, the sam manager initialization relies on the observable mechanism. I can imagine cases where it can be a problem. It would be more robust if the initialization would be static and then rely on observability for dynamic changes. #staticinit
- lacks unit testing

**Comment by pterr** [comment]
Yes, when no resource is available, the SAM Manager may return an exception instead of null.

The 'SAM Manager' is a Calypso high level API to obtain "SAM resources".
There could be mainly 3 ways to interface a native SAM to the SAM Manager:

- SAM instances could be provided by a Calypso HSM: in this case the SAM Manager operates a ReaderPoolPlugin.
- SAM instances could also be provided locally through PC/SC readers: in this case the SAM Manager operates a ReaderPlugin.
    - we may allow to allocate only some specific PC/SC readers to the SAM Manager.
    - the flexibility of PC/SC is to allow the hot plug of readers and the acceptance of newly inserted SAM without rebooting the SAM Manager.
 - SAM instances could also be interfaced remotely through the Remote SE plugin.

If the SAM Manager is defined as a singleton, it may allow to be interfaced with a mix different plugin (HSM, PC/SC, Remote SE).

The SAM Manager object couldn’t be declared to the SE Proxy: the Core API shouldn’t have dependency with the Calypso API.

The behavior of the HSM and PC/SC plugins are different:
 - for an HSM, as a ReaderPoolPlugin, we can't get the full list of SAM instances, but we can request the allocation of a SAM instance and release: exactly the service proposed by the SAM Manager.
 - for the PC/SC, by observing the PC/SC plugin and the PC/SC reader, the SAM Manager has the possibility to recover a list of PC/SC reader, but SAM Manager not necessary needs to handle all the available PC/SC readers, maybe only a subset. Using https://github.com/eclipse/keyple-java/issues/194 the SAM Manager may be able to shortlist only some specific readers, or using https://github.com/eclipse/keyple-java/issues/195 the SAM Manager has the possibility to be notified for events of some specific readers (ATR filter specific for SAM). For PC/SC, the SAM Manager has to manage identified PC/SC readers like ReaderPoolPlugin does (cf. https://github.com/eclipse/keyple-java/issues/148).
The goal of the SAM Manager is to hide the specificities of the SAM suppliers, and to provide SAM resources in a generic way (potentially SAM resources from different suppliers). The SAM Manager may be able to handle several plugins at a time.

**Comment by odelcroi** [comment]
#259 created
