### ISSUE TITLE
How to unlock a SAM

### ISSUE THREAD

**Issue by zemoa** [eclipse/keyple-java#361]
Hello,

I want to write some data on a secure element with a SAM.
I follow the example provided in `PoAuthentication_Pcsc` but, my SAMis locked and, of course, the method `processOpening` fail.
I have the key to unlocking my SAM but I can't find how to use it with your framework, can you help me?

**Comment by jeanpierrefortune** [comment]
Hello zemoa,
Thank you for your interest in Keyple.
Unfortunately the high level API to handle this type of operations with the SAM is under development and will not be available in the very short term.
However, it is possible to perform the unlocking of the SAM using the low level commands as shown below :

```
            // create an apdu request list to handle SAM command
            List<ApduRequest> apduRequests = new ArrayList<ApduRequest>();

            final String UNLOCK_DATA = "00112233445566778899AABBCCDDEEFF";

            // create a request with the Unlock command builder
            apduRequests.add(new UnlockCmdBuild(SamRevision.C1, ByteArrayUtil.fromHex(UNLOCK_DATA))
                    .getApduRequest());

            SeRequest seRequest = new SeRequest(apduRequests);

            SeResponse seResponse = ((ProxyReader) samResource.getSeReader())
                    .transmitSeRequest(seRequest, ChannelControl.KEEP_OPEN);

            if (seResponse.getApduResponses().get(0).getStatusCode() != 0x9000) {
                System.out.println("The SAM unlocking failed!");
            } else {
                System.out.println("The SAM unlocking was successful!");
            }
```
You should be able to implement your own method to unlock the SAM.
Feel free to keep us informed.

**Comment by zemoa** [comment]
Thank you for your answer.
Actually, I use v0.8.1 and I don't find the method `transmitSeRequest`, but it seems to works with this code :
`((ProxyReader) samResource.getSeReader()).transmit(seRequest)`

I will try with your new version "0.9.0"

**Comment by jeanpierrefortune** [comment]
Hello zemoa,
The easiest way to use the latest `'develop'` version of Keyple is to specify this in a `gradle.properties` file (to be placed next to `build.gradle`).
For example:
```
keyple_version=0.9.0-SNAPSHOT
```
It is also possible to be more specific about targeting a particular date of SNAPSHOT by changing `keyple_v` in each dependency declaration defined in `build.gradle`.

```
    implementation group: 'org.eclipse.keyple', name: 'keyple-java-core', version: '0.9.0-20200710.143658-40'
    implementation group: 'org.eclipse.keyple', name: 'keyple-java-calypso', version: '0.9.0-20200710.143713-40'
    implementation group: 'org.eclipse.keyple', name: 'keyple-java-plugin-pcsc', version: '0.9.0-20200710.143750-40'
    implementation group: 'org.eclipse.keyple', name: 'keyple-java-plugin-stub', version: '0.9.0-20200710.143839-40'
```
Note that due to timestamp naming, the CI produces SNAPSHOT version numbers that are not quite identical for each module.
The SNAPSHOT repository can be found here:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/keyple/
The files to be taken into account are those prefixed by 'keyple-java'.
